/**
 * FOCUS Quiz Module — Seed Data
 * Sample subjects, topics, and questions across all 5 question types.
 * Used to bootstrap the mock database on first access.
 */

export function getQuizSeedData() {
  const subjects = [
    { id: 'subj-cs', name: 'Computer Science' },
    { id: 'subj-math', name: 'Mathematics' },
  ];

  const topics = [
    // Computer Science
    { id: 'topic-ds', subjectId: 'subj-cs', name: 'Data Structures' },
    { id: 'topic-algo', subjectId: 'subj-cs', name: 'Algorithms' },
    { id: 'topic-web', subjectId: 'subj-cs', name: 'Web Development' },
    // Mathematics
    { id: 'topic-calc', subjectId: 'subj-math', name: 'Calculus' },
    { id: 'topic-la', subjectId: 'subj-math', name: 'Linear Algebra' },
    { id: 'topic-prob', subjectId: 'subj-math', name: 'Probability' },
  ];

  const questions = [
    // ── Computer Science: Data Structures ───────────────────────────

    // MCQ
    {
      id: 'q-ds-1',
      subjectId: 'subj-cs',
      topicId: 'topic-ds',
      difficulty: 'easy',
      type: 'mcq',
      question: 'Which data structure follows the Last-In-First-Out (LIFO) principle?',
      payload: { options: ['Queue', 'Stack', 'Linked List', 'Tree'] },
      correctAnswer: { correct: 1 },
      explanation: 'A Stack follows LIFO — the last element added is the first one removed, like a stack of plates.',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-ds-2',
      subjectId: 'subj-cs',
      topicId: 'topic-ds',
      difficulty: 'medium',
      type: 'mcq',
      question: 'What is the average time complexity of searching in a balanced Binary Search Tree?',
      payload: { options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'] },
      correctAnswer: { correct: 1 },
      explanation: 'In a balanced BST, the height is O(log n), so searching, insertion, and deletion all take O(log n) on average.',
      marks: 3,
      negativeMarks: 0.75,
    },

    // True/False
    {
      id: 'q-ds-3',
      subjectId: 'subj-cs',
      topicId: 'topic-ds',
      difficulty: 'easy',
      type: 'true-false',
      question: 'A linked list allows constant-time access to any element by index.',
      payload: { statement: 'A linked list allows constant-time access to any element by index.' },
      correctAnswer: { correct: false },
      explanation: 'Linked lists require O(n) traversal to access elements by index, unlike arrays which provide O(1) indexed access.',
      marks: 1,
      negativeMarks: 0.25,
    },

    // Fill in the blank
    {
      id: 'q-ds-4',
      subjectId: 'subj-cs',
      topicId: 'topic-ds',
      difficulty: 'medium',
      type: 'fill-blank',
      question: 'A ___ is a data structure that maps keys to values using a hash function.',
      payload: { text: 'A ___ is a data structure that maps keys to values using a hash function.' },
      correctAnswer: { answers: ['hash table'], alternatives: [['hash map', 'hashmap', 'hashtable', 'dictionary']] },
      explanation: 'A hash table (or hash map) uses a hash function to compute an index where the value is stored, providing average O(1) lookups.',
      marks: 2,
      negativeMarks: 0.5,
    },

    // One-word
    {
      id: 'q-ds-5',
      subjectId: 'subj-cs',
      topicId: 'topic-ds',
      difficulty: 'hard',
      type: 'one-word',
      question: 'What type of tree is always perfectly balanced and used in databases for disk-based storage?',
      payload: {},
      correctAnswer: { correct: 'B-tree', alternatives: ['B tree', 'btree', 'b-tree'] },
      explanation: 'B-trees are self-balancing search trees designed for systems that read/write large blocks of data, commonly used in databases and file systems.',
      marks: 3,
      negativeMarks: 1,
    },

    // ── Computer Science: Algorithms ────────────────────────────────

    {
      id: 'q-algo-1',
      subjectId: 'subj-cs',
      topicId: 'topic-algo',
      difficulty: 'easy',
      type: 'mcq',
      question: 'Which sorting algorithm has a worst-case time complexity of O(n²)?',
      payload: { options: ['Merge Sort', 'Bubble Sort', 'Heap Sort', 'Counting Sort'] },
      correctAnswer: { correct: 1 },
      explanation: 'Bubble Sort compares adjacent elements and swaps them, leading to O(n²) comparisons in the worst case.',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-algo-2',
      subjectId: 'subj-cs',
      topicId: 'topic-algo',
      difficulty: 'medium',
      type: 'mcq',
      question: 'What algorithmic paradigm does Merge Sort follow?',
      payload: { options: ['Dynamic Programming', 'Greedy', 'Divide and Conquer', 'Backtracking'] },
      correctAnswer: { correct: 2 },
      explanation: 'Merge Sort divides the array into halves, recursively sorts each half, then merges them — a classic Divide and Conquer approach.',
      marks: 3,
      negativeMarks: 0.75,
    },
    {
      id: 'q-algo-3',
      subjectId: 'subj-cs',
      topicId: 'topic-algo',
      difficulty: 'hard',
      type: 'true-false',
      question: 'Dijkstra\'s algorithm works correctly with graphs that have negative edge weights.',
      payload: { statement: 'Dijkstra\'s algorithm works correctly with graphs that have negative edge weights.' },
      correctAnswer: { correct: false },
      explanation: 'Dijkstra\'s algorithm assumes non-negative edge weights. For graphs with negative weights, use Bellman-Ford algorithm.',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-algo-4',
      subjectId: 'subj-cs',
      topicId: 'topic-algo',
      difficulty: 'medium',
      type: 'fill-blank',
      question: 'The time complexity of binary search on a sorted array is ___.',
      payload: { text: 'The time complexity of binary search on a sorted array is ___.' },
      correctAnswer: { answers: ['O(log n)'], alternatives: [['o(log n)', 'O(logn)', 'o(logn)']] },
      explanation: 'Binary search halves the search space in each step, resulting in logarithmic time complexity O(log n).',
      marks: 2,
      negativeMarks: 0.5,
    },

    // Match
    {
      id: 'q-algo-5',
      subjectId: 'subj-cs',
      topicId: 'topic-algo',
      difficulty: 'hard',
      type: 'match',
      question: 'Match each algorithm with its time complexity:',
      payload: {
        leftItems: ['Binary Search', 'Merge Sort', 'Linear Search', 'Quick Sort (avg)'],
        rightItems: ['O(n)', 'O(n log n)', 'O(log n)', 'O(n log n)'],
      },
      correctAnswer: { mapping: [2, 1, 0, 3] },
      explanation: 'Binary Search: O(log n), Merge Sort: O(n log n), Linear Search: O(n), Quick Sort average: O(n log n).',
      marks: 4,
      negativeMarks: 1,
    },

    // ── Computer Science: Web Development ───────────────────────────

    {
      id: 'q-web-1',
      subjectId: 'subj-cs',
      topicId: 'topic-web',
      difficulty: 'easy',
      type: 'mcq',
      question: 'What does HTML stand for?',
      payload: { options: ['Hyper Text Markup Language', 'High Tech Multi Language', 'Hyper Transfer Markup Language', 'Home Tool Markup Language'] },
      correctAnswer: { correct: 0 },
      explanation: 'HTML stands for HyperText Markup Language — the standard markup language for creating web pages.',
      marks: 1,
      negativeMarks: 0.25,
    },
    {
      id: 'q-web-2',
      subjectId: 'subj-cs',
      topicId: 'topic-web',
      difficulty: 'medium',
      type: 'true-false',
      question: 'CSS Flexbox and Grid are both used for creating responsive layouts in web pages.',
      payload: { statement: 'CSS Flexbox and Grid are both used for creating responsive layouts in web pages.' },
      correctAnswer: { correct: true },
      explanation: 'Both Flexbox (one-dimensional) and Grid (two-dimensional) are CSS layout modules designed for building responsive web layouts.',
      marks: 1,
      negativeMarks: 0.25,
    },
    {
      id: 'q-web-3',
      subjectId: 'subj-cs',
      topicId: 'topic-web',
      difficulty: 'medium',
      type: 'one-word',
      question: 'Which JavaScript keyword is used to declare a block-scoped variable that cannot be reassigned?',
      payload: {},
      correctAnswer: { correct: 'const', alternatives: [] },
      explanation: '`const` declares a block-scoped variable whose value cannot be reassigned after initialisation (though object properties can still be modified).',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-web-4',
      subjectId: 'subj-cs',
      topicId: 'topic-web',
      difficulty: 'hard',
      type: 'match',
      question: 'Match each HTTP status code with its meaning:',
      payload: {
        leftItems: ['200', '404', '500', '301'],
        rightItems: ['Moved Permanently', 'OK', 'Not Found', 'Internal Server Error'],
      },
      correctAnswer: { mapping: [1, 2, 3, 0] },
      explanation: '200 = OK, 404 = Not Found, 500 = Internal Server Error, 301 = Moved Permanently.',
      marks: 4,
      negativeMarks: 1,
    },
    {
      id: 'q-web-5',
      subjectId: 'subj-cs',
      topicId: 'topic-web',
      difficulty: 'easy',
      type: 'fill-blank',
      question: 'The ___ tag in HTML is used to create hyperlinks to other web pages.',
      payload: { text: 'The ___ tag in HTML is used to create hyperlinks to other web pages.' },
      correctAnswer: { answers: ['<a>'], alternatives: [['a', 'anchor', '<a']] },
      explanation: 'The <a> (anchor) tag defines a hyperlink, which is used to link from one page to another using the href attribute.',
      marks: 1,
      negativeMarks: 0.25,
    },

    // ── Mathematics: Calculus ───────────────────────────────────────

    {
      id: 'q-calc-1',
      subjectId: 'subj-math',
      topicId: 'topic-calc',
      difficulty: 'easy',
      type: 'mcq',
      question: 'What is the derivative of x²?',
      payload: { options: ['x', '2x', '2x²', 'x²'] },
      correctAnswer: { correct: 1 },
      explanation: 'Using the power rule: d/dx(xⁿ) = nxⁿ⁻¹. So d/dx(x²) = 2x.',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-calc-2',
      subjectId: 'subj-math',
      topicId: 'topic-calc',
      difficulty: 'medium',
      type: 'fill-blank',
      question: 'The integral of 1/x dx is ___ + C.',
      payload: { text: 'The integral of 1/x dx is ___ + C.' },
      correctAnswer: { answers: ['ln|x|'], alternatives: [['ln(x)', 'lnx', 'ln x', 'log x', 'natural log of x']] },
      explanation: 'The integral ∫(1/x)dx = ln|x| + C, where ln is the natural logarithm.',
      marks: 3,
      negativeMarks: 0.75,
    },
    {
      id: 'q-calc-3',
      subjectId: 'subj-math',
      topicId: 'topic-calc',
      difficulty: 'easy',
      type: 'true-false',
      question: 'The derivative of a constant is always zero.',
      payload: { statement: 'The derivative of a constant is always zero.' },
      correctAnswer: { correct: true },
      explanation: 'A constant has no rate of change, so its derivative is 0. d/dx(c) = 0 for any constant c.',
      marks: 1,
      negativeMarks: 0.25,
    },
    {
      id: 'q-calc-4',
      subjectId: 'subj-math',
      topicId: 'topic-calc',
      difficulty: 'hard',
      type: 'one-word',
      question: 'What theorem states that if f is continuous on [a,b], then there exists a c in (a,b) such that f\'(c) = (f(b)-f(a))/(b-a)?',
      payload: {},
      correctAnswer: { correct: 'Mean Value Theorem', alternatives: ['MVT', 'mean value', 'mean value theorem'] },
      explanation: 'The Mean Value Theorem guarantees that for a continuous and differentiable function, there\'s at least one point where the instantaneous rate of change equals the average rate of change.',
      marks: 3,
      negativeMarks: 1,
    },
    {
      id: 'q-calc-5',
      subjectId: 'subj-math',
      topicId: 'topic-calc',
      difficulty: 'medium',
      type: 'mcq',
      question: 'What is the derivative of sin(x)?',
      payload: { options: ['-cos(x)', 'cos(x)', 'tan(x)', '-sin(x)'] },
      correctAnswer: { correct: 1 },
      explanation: 'The derivative of sin(x) is cos(x). This is one of the fundamental differentiation rules.',
      marks: 2,
      negativeMarks: 0.5,
    },

    // ── Mathematics: Linear Algebra ─────────────────────────────────

    {
      id: 'q-la-1',
      subjectId: 'subj-math',
      topicId: 'topic-la',
      difficulty: 'easy',
      type: 'mcq',
      question: 'What is the determinant of a 2×2 identity matrix?',
      payload: { options: ['0', '1', '2', '-1'] },
      correctAnswer: { correct: 1 },
      explanation: 'The identity matrix I has 1s on the diagonal and 0s elsewhere. det(I) = (1)(1) - (0)(0) = 1.',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-la-2',
      subjectId: 'subj-math',
      topicId: 'topic-la',
      difficulty: 'medium',
      type: 'true-false',
      question: 'Two vectors are orthogonal if their dot product is zero.',
      payload: { statement: 'Two vectors are orthogonal if their dot product is zero.' },
      correctAnswer: { correct: true },
      explanation: 'Orthogonal (perpendicular) vectors have a dot product of 0: u·v = 0 means the angle between them is 90°.',
      marks: 1,
      negativeMarks: 0.25,
    },
    {
      id: 'q-la-3',
      subjectId: 'subj-math',
      topicId: 'topic-la',
      difficulty: 'hard',
      type: 'match',
      question: 'Match each matrix operation with its property:',
      payload: {
        leftItems: ['Transpose', 'Inverse', 'Determinant', 'Trace'],
        rightItems: ['Sum of diagonal elements', 'Rows become columns', 'AA⁻¹ = I', 'Scalar value from square matrix'],
      },
      correctAnswer: { mapping: [1, 2, 3, 0] },
      explanation: 'Transpose: rows↔columns. Inverse: AA⁻¹=I. Determinant: scalar from square matrix. Trace: sum of diagonal.',
      marks: 4,
      negativeMarks: 1,
    },
    {
      id: 'q-la-4',
      subjectId: 'subj-math',
      topicId: 'topic-la',
      difficulty: 'easy',
      type: 'one-word',
      question: 'What do we call the values of λ for which Av = λv has non-trivial solutions?',
      payload: {},
      correctAnswer: { correct: 'eigenvalues', alternatives: ['eigen values', 'eigenvalue'] },
      explanation: 'Eigenvalues (λ) are scalars such that Av = λv for some non-zero vector v (the eigenvector).',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-la-5',
      subjectId: 'subj-math',
      topicId: 'topic-la',
      difficulty: 'medium',
      type: 'fill-blank',
      question: 'The number of linearly independent rows in a matrix is called its ___.',
      payload: { text: 'The number of linearly independent rows in a matrix is called its ___.' },
      correctAnswer: { answers: ['rank'], alternatives: [['matrix rank']] },
      explanation: 'The rank of a matrix is the dimension of the vector space spanned by its rows (or columns), equal to the number of linearly independent rows.',
      marks: 2,
      negativeMarks: 0.5,
    },

    // ── Mathematics: Probability ────────────────────────────────────

    {
      id: 'q-prob-1',
      subjectId: 'subj-math',
      topicId: 'topic-prob',
      difficulty: 'easy',
      type: 'mcq',
      question: 'What is the probability of getting heads when flipping a fair coin?',
      payload: { options: ['0.25', '0.5', '0.75', '1'] },
      correctAnswer: { correct: 1 },
      explanation: 'A fair coin has two equally likely outcomes (heads/tails), so P(heads) = 1/2 = 0.5.',
      marks: 1,
      negativeMarks: 0.25,
    },
    {
      id: 'q-prob-2',
      subjectId: 'subj-math',
      topicId: 'topic-prob',
      difficulty: 'medium',
      type: 'true-false',
      question: 'For independent events A and B, P(A ∩ B) = P(A) × P(B).',
      payload: { statement: 'For independent events A and B, P(A ∩ B) = P(A) × P(B).' },
      correctAnswer: { correct: true },
      explanation: 'By definition, events A and B are independent if and only if P(A ∩ B) = P(A) × P(B).',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-prob-3',
      subjectId: 'subj-math',
      topicId: 'topic-prob',
      difficulty: 'hard',
      type: 'fill-blank',
      question: 'Bayes\' theorem states that P(A|B) = P(B|A) × P(A) / ___.',
      payload: { text: 'Bayes\' theorem states that P(A|B) = P(B|A) × P(A) / ___.' },
      correctAnswer: { answers: ['P(B)'], alternatives: [['p(b)', 'P(b)', 'p(B)']] },
      explanation: 'Bayes\' theorem: P(A|B) = P(B|A) × P(A) / P(B). P(B) is the marginal probability of event B.',
      marks: 3,
      negativeMarks: 0.75,
    },
    {
      id: 'q-prob-4',
      subjectId: 'subj-math',
      topicId: 'topic-prob',
      difficulty: 'medium',
      type: 'mcq',
      question: 'If two dice are rolled, how many possible outcomes are there?',
      payload: { options: ['6', '12', '36', '24'] },
      correctAnswer: { correct: 2 },
      explanation: 'Each die has 6 faces. By the multiplication principle: 6 × 6 = 36 possible outcomes.',
      marks: 2,
      negativeMarks: 0.5,
    },
    {
      id: 'q-prob-5',
      subjectId: 'subj-math',
      topicId: 'topic-prob',
      difficulty: 'easy',
      type: 'one-word',
      question: 'What is the expected value also commonly called in statistics?',
      payload: {},
      correctAnswer: { correct: 'mean', alternatives: ['average', 'expectation', 'expected value'] },
      explanation: 'The expected value (E[X]) is also known as the mean or average — it represents the long-run average outcome of a random variable.',
      marks: 1,
      negativeMarks: 0.25,
    },
  ];

  return { subjects, topics, questions };
}
